plugin:
  dive:
    shortCut: d
    confirm: false
    description: "Dive image"
    scopes:
      - containers
    command: dive
    background: false
    args:
      - $COL-IMAGE
  #get all resources in a namespace using the krew get-all plugin
  get-all-namespace:
    shortCut: g
    confirm: false
    description: get-all
    scopes:
    - namespaces
    command: sh
    background: false
    args:
    - -c
    - "kubectl get-all -n $NAME | less"
  get-all-other:
    shortCut: g
    confirm: false
    description: get-all
    scopes:
    - all
    command: sh
    background: false
    args:
    - -c
    - "kubectl get-all -n $NAMESPACE | less"
  helm-values:
    shortCut: v
    confirm: false
    description: Values
    scopes:
    - helm
    command: sh
    background: false
    args:
    - -c
    - "helm get values $COL-NAME -n $NAMESPACE --kube-context $CONTEXT | less"
  watch-events:
    shortCut: Shift-E
    confirm: false
    description: Get Events
    scopes:
    - all
    command: sh
    background: false
    args:
    - -c
    - "watch -n 5 kubectl get events --context $CONTEXT --namespace $NAMESPACE --field-selector involvedObject.name=$NAME"
